finalproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^guru/', include('guru.urls')),
    url(r'^$', 'guru.views.home'),
]

guru/urls.py
from django.conf.urls import include, url, patterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', 'guru.views.home', name='home'),
    url(r'^login$', 'django.contrib.auth.views.login', {'template_name':'guru/login.html'}, name='login'),
    url(r'^logout$', 'django.contrib.auth.views.logout_then_login', name='logout'),
    url(r'^register$', 'guru.views.register', name='register'),
    url(r'^inbox$', 'guru.views.inbox', name='inbox'),
    url(r'^reminders$', 'guru.views.reminders', name='reminders'),
    url(r'^calendar$', 'guru.views.calendar', name='calendar'),
    url(r'^myreviews$', 'guru.views.myreviews', name='myreviews'),
    url(r'^settings$', 'guru.views.settings', name='settings'),
    url(r'^searchresults$', 'guru.views.searchresults', name='searchresults'),
    url(r'^postdetails/(?P<id>\d+)$', 'guru.views.postdetails', name='postdetails'),
    url(r'^profile/(?P<id>\d+)$', 'guru.views.profile', name='profile'),
    url(r'^profile/(?P<username>\w+)$', 'guru.views.pprofile', name='pprofile'),
    url(r'^editprofile', 'guru.views.editprofile', name='editprofile'),
    url(r'^newuser$', 'guru.views.createNewUser', name='newuser'),
    url(r'^reset$', 'guru.views.reset', name='resetpasswordrender'),
    url(r'^resetpassword$', 'guru.views.resetpassword', name='resetpassword'),
    url(r'^newlisting$', 'guru.views.newListing', name='newlisting'),
    url(r'^Interest$', 'guru.views.addInterests', name='addInterests'),
    url(r'^alllistings$', 'guru.views.allListings', name='allListings'),
    url(r'^addlisting$', 'guru.views.addlisting', name='addlisting'),
    url(r'^compose$', 'guru.views.compose', name='compose'),
    url(r'^compose/(?P<id>\d+)$', 'guru.views.lcompose', name='lcompose'),
    url(r'getusernames$', 'guru.views.getusernames', name='getusernames'),
    url(r'sendmessage$', 'guru.views.sendmessage', name='sendmessage'),
    url(r'sendreply$', 'guru.views.sendreply', name='sendreply'),
    url(r'^message/(?P<id>\d+)$', 'guru.views.messageExpanded', name='messageExpanded'),
    url(r'^interested/(?P<id>\d+)$', 'guru.views.interested', name='interested'),
    url(r'^uninterested/(?P<id>\d+)$', 'guru.views.uninterested', name='uninterested'),
    url(r'^activity$', 'guru.views.activity', name='activity'),
    url(r'^dismiss-request/(?P<reqInfo>\w+)$', 'guru.views.dismissRequest', name='dismissRequest'),
    url(r'^confirm-request$', 'guru.views.confirmRequest', name='confirmRequest'),
    url(r'^saveInterests$', 'guru.views.saveInterests', name='saveInterests'),
    url(r'^schedule/(?P<listingId>\d+)/(?P<guruId>\d+)$', 'guru.views.schedule', name='schedule'),
    url(r'^schedule/(?P<listingId>\d+)$', 'guru.views.studentSchedule', name='studentSchedule'),
    url(r'^add-date$', 'guru.views.add_date', name='addDate'),
    url(r'^delete-date/(?P<id>\d+)$', 'guru.views.delete_date', name='deleteDate'),
    url(r'^get-dates$', 'guru.views.get_dates', name='getDates'),
    url(r'^confirm-date$', 'guru.views.confirm_date', name='confirmDate'),
    url(r'^dismiss-sched$', 'guru.views.dismiss_sched', name='dismissSched'),
    url(r'^confirm-sched$', 'guru.views.confirm_sched', name='confirmSched'),
    url(r'^updateInterests$', 'guru.views.updateInterests', name='updateInterests'),
    url(r'^review/(?P<sessionId>\d+)$', 'guru.views.reviewSession', name='reviewSession'),
    url(r'^postReview$', 'guru.views.postReview', name='postReview'),
    url(r'getcategories$', 'guru.views.getcategories', name='getcategories'),
    url(r'sendtext$', 'guru.views.sendtext', name='sendtext'),
    url(r'search$', 'guru.views.search', name='search'),
    url(r'^get-relevantInterest$', 'guru.views.get_relevantInterest', name='getrelevantInterest'),
]

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

guru/models.py
from django.db import models
from django.utils import timezone
from django.db.models import Max
from django.utils.html import escape

# User class for built-in authentication module
from django.contrib.auth.models import User

class Credit(models.Model):
	hoursLearned = models.IntegerField(null=True)
	hoursTaught = models.IntegerField(null=True)

class Guru(models.Model):
	user = models.OneToOneField(User)
	location = models.CharField(max_length=50)
	rating = models.FloatField(null=True)
	level = models.CharField(max_length=50)
	followers = models.ManyToManyField("self", related_name="followers")
	following = models.ManyToManyField("self", related_name="following")
	picture = models.ImageField(blank=True, upload_to="guru-photos", default="/media/guru-photos/person.jpg")
	skills = models.CharField(max_length=500) 
	bio = models.CharField(max_length=400)
	age = models.IntegerField(null=True)
	credit = models.OneToOneField(Credit)
	interested = models.ManyToManyField('Listing', related_name = 'interested', default=None)
	needsConfirmation = models.ManyToManyField('Listing', related_name = 'needsConfirmation', default=None)
	rejected = models.ManyToManyField('Listing', related_name = 'rejected', default=None)
	confirmed = models.ManyToManyField('Listing', related_name = 'confirmed', default=None)
	reviewsReceived = models.IntegerField(default=0)


class Listing(models.Model): 
	subject = models.CharField(max_length=42)
	location = models.CharField(max_length=50, default="N/A")
	description = models.CharField(max_length=500)
	guru = models.ForeignKey(Guru)
	date = models.DateTimeField(default=timezone.now)
	skillType = models.CharField(max_length=40)
	#session = models.ForeignKey('MySession', default=None, null=True) # a session has many listings
	#session = models.ManyToManyField('MySession', default=None, null=True)

class DateAndTime(models.Model):
	date = models.CharField(max_length=20)
	fromTime = models.CharField(max_length=5) # 24 hr time?
	toTime = models.CharField(max_length=5)
	instructorTimes = models.ManyToManyField('MySession', related_name = 'instructorTimes', default=None)
	studentTimes = models.ManyToManyField('MySession', related_name = 'studentTimes', default=None)

class MySession(models.Model):
	#listing = models.ManyToManyField('Listing', related_name='listing', default=None)
	student = models.ManyToManyField('Guru', related_name='student', default=None)
	listing = models.OneToOneField(Listing, related_name='listing')
	#student = models.OneToOneField(Guru, related_name = 'student')
	#listing = models.ForeignKey(Listing)
	#student = models.ForeignKey(Guru)
	status = models.CharField(max_length=20, default="N/A") # pending, confirmed, rejected
	proposedTime = models.CharField(max_length=30, default="N/A")
	progress = models.CharField(max_length=20, default="N/A") # in progress, completed, upcoming
	reviewed = models.BooleanField(default=False)

class Review(models.Model): 
	session = models.OneToOneField(MySession, related_name = 'session')
	#guru = models.OneToOneField(Guru, related_name = 'reviewer')
	#reviewedUser = models.OneToOneField(Guru, related_name = 'reviewee')
	rating = models.FloatField(null=True)
	date = models.DateTimeField(default=timezone.now)
	description = models.CharField(max_length=500)

class Message(models.Model):
	fromGuru = models.ForeignKey(Guru, related_name = 'fromGuru')
	toGuru = models.ForeignKey(Guru, related_name = 'toGuru')
	date = models.DateTimeField(default=timezone.now)
	subject = models.CharField(max_length=100)
	body = models.TextField(null=True)
	numReplies = models.IntegerField(default=1)

class Reply(models.Model):
	fromGuru = models.ForeignKey(Guru, related_name = 'fromReply')
	toGuru = models.ForeignKey(Guru, related_name = 'toReply')
	message = models.ForeignKey(Message)
	date = models.DateTimeField(default=timezone.now)
	body = models.TextField(null=True)

class Person(models.Model):
	usernames = models.CharField(max_length=20)
	skills = models.CharField(max_length=500) 
	timestamp = models.DateTimeField(default=timezone.now)

class Interest(models.Model):
	username = models.CharField(max_length=20)
	interestList = models.CharField(max_length=2000)

guru/forms.py
from django.forms import ModelForm
from guru.models import *
from django import forms
from django.contrib.auth.models import User

class RegistrationForm(forms.Form):
	email = forms.EmailField(max_length=40)
	username = forms.CharField(max_length=20)
	password = forms.CharField(widget=forms.PasswordInput())
	confirmpassword = forms.CharField(widget=forms.PasswordInput())
	firstname = forms.CharField(max_length=20)
	lastname = forms.CharField(max_length=20)

	def clean(self):
		cleaned_data = super(RegistrationForm, self).clean()
		email = cleaned_data.get('email')
		username = cleaned_data.get('username')
		password = cleaned_data.get('password')
		confirmpassword = cleaned_data.get('confirmpassword')
		
		if password != confirmpassword:
			raise forms.ValidationError("passwords does not match")
		if email and User.objects.filter(email__exact=email):
			raise forms.ValidationError("email is already taken")
		if username and User.objects.filter(username__exact=username):
			raise forms.ValidationError("username already taken")
		return cleaned_data

class ResetForm(forms.Form):
	email = forms.EmailField(max_length=40)
	def clean(self):
		cleaned_data = super(ResetForm, self).clean()
		cleanEmail = cleaned_data.get('email') #only need to check if email exists
		if( cleanEmail and User.objects.filter(email=cleanEmail).count() != 1):
			raise forms.ValidationError("Email not registered")
		return cleaned_data

class EditProfileForm(forms.ModelForm):
	class Meta:
		model = Guru
		exclude = ('user', )
		fields = ['location', 'skills', 'age', 'bio', 'picture']
		widgets = {'picture' : forms.FileInput() }
	
	def clean(self): #nothing besides age needs to be cleaned
		cleaned_data = super(EditProfileForm, self).clean()
		age = cleaned_data.get('age') 
		if( age < 5 or age > 120): #check age range
			raise forms.ValidationError("Please enter a valid age")
		return cleaned_data

class ListingForm(forms.ModelForm):
	class Meta:
		model = Listing
		fields = ['subject','location','description']
	def clean(self):
		cleaned_data = super(ListingForm, self).clean()
		#nothing much to clean except checking size of input non-null
		subj = cleaned_data.get('subject')
		if (len(subj) < 1):
			raise forms.ValidationError("Subject must not be empty")
		location = cleaned_data.get('location')
		if (len(location) < 1):
			raise forms.ValidationError("location must not be empty")
		description = cleaned_data.get('description')
		if (len(description) < 1):
			raise forms.ValidationError("description must not be empty")
		return cleaned_data


class PersonForm(forms.ModelForm):
	class Meta:
		model = Person #Form used for search engine, no need for cleaning
		fields = ('usernames',)
		

guru/templates/guru/activity.html
{% extends "guru/base.html" %}
{% load staticfiles %}

{% block title %}
<title> guru | my activity </title>
{% endblock %}

{% block mainsection %}
<div class="row">
  <div class="col s12">
    <ul class="tabs">
      <li class="tab col s3"><a class="active" href="#interested">Sessions to Learn</a></li>
      <li class="tab col s3"><a href="#schedule">Sessions to Teach</a></li>
      <li class="tab col s3"><a href="#calendar">Calendar</a></li>
      <li class="tab col s3"><a href="#reminders">Reminders</a></li>
    </ul>
  </div>

  <div id="interested" class="col s12">


    <br>
      <table class="responsive-table">
        <thead>
          <tr>
              <th>Session Name</th>
              <th>Instructor</th>
              <th>Status</th>
              <th>Details</th>
          </tr>
        </thead>
       

       <tbody>
        {% if pending %}
          {% for p in pending %}
          <tr>
          <td>{{p.subject}}</td>
          <td>{{p.guru.user.username}}</td>
          <td>Pending</td>
          <td>N/A</td>
        </tr>
        {% endfor %}
        {% endif %}

        {% if rejections %}
          {% for rejection in rejections %}
          <tr>
          <td>{{rejection.subject}}</td>
          <td>{{rejection.guru.user.username}}</td>
          <td>Rejected</td>
          <td>N/A</td>
        </tr>
        {% endfor %}
        {% endif %}

        {% if confirmed %}
        {% for c in confirmed %}
          <tr>
          <td>{{c.subject}}</td>
          <td>{{c.guru.user.username}}</td>
          <td>Confirmed</td>
          <td><a href="/guru/schedule/{{c.id}}"><i class="fa fa-plus-square-o fa-2x"></i></td>
        </tr>
        {% endfor %}
        {% endif %}
        </tbody>

      </table>

  </div>



  <div id="schedule" class="col s12">
    {% if requests.items %}
    Requesting your confirmation
    <ul class="collection">
      {% for key, value in requests.items %}
        {% for i in value %}
          
      <li class="collection-item avatar">
        <img src="/guru{{key.0.picture.url}}" alt="{{key.0.picture.url}}" class="circle">
        <span class="title">{{i.subject}}</span>
        <p>{{key.0.user.username}} 
        </p>
        
        <div class="secondary-content">
          <a href="#!"  onclick="dismissRequest(this)"><i class="fa fa-times fa-2x" style="color:red;"></i></a>
          <a href="#!" onclick="confirmRequest(this)"><i class="fa fa-check fa-2x" style="color:green;"></i></a>
        </div>
      </li>
      {% endfor %}
      {% endfor %}
    </ul>
    {% endif %}

   <h4>Completed Sessions</h4>
      <table class="responsive-table table1">
        <thead>
          <tr>
              <th>Session Name</th>
              <th>Student</th>
              <th>Status</th>
              <th>Progress</th>
              <th>Details</th>
          </tr>
        </thead>
        <tbody>
        {% if completedData.items %}
        {% for key, value in completedData.items %}
           <tr>
            <td>{{value.listing.subject}}</td>
            <td>{{value.student.user.username}}</td>
            <td>{{value.progress}}
            <td>{{value.status}}</td>
            <td><a href="/guru/schedule/{{value.listing.id}}/{{value.student.all.0.id}}"><i class="fa fa-plus-square-o fa-2x"></i></a> </td>

          </tr>
          {% endfor %}
          {% endif %}
        </tbody>
      </table>


    <h4>Upcoming Sessions to Teach</h4>
      <table class="responsive-table table2">
        <thead>
          <tr>
              <th>Session Name</th>
              <th>Student</th>
              <th>Status</th>
              <th>Progress</th>
              <th>Details</th>
          </tr>
        </thead>
        <tbody>
        {% if upcomingData.items %}
        {% for key, value in upcomingData.items %}
           <tr>
            <td>{{value.listing.subject}}</td>
            <td>{{value.student.user.username}}</td>
            <td>{{value.progress}}
            <td>{{value.status}}</td>
            <td><a href="/guru/schedule/{{value.listing.id}}/{{value.student.all.0.id}}"><i class="fa fa-plus-square-o fa-2x"></i></a> </td>

          </tr>
          {% endfor %}
        {% endif %}
        </tbody>
      </table>
  </div>

  <div id="calendar" class="col s12">Calendar

  <div id="datetimepicker4" class="input-append">
    <div class="col s1">
      <span class="add-on">
      <i class="fa fa-calendar fa-2x" data-time-icon="icon-time" data-date-icon="icon-calendar">
      </i>
    </span>
    </div>
    <div class="col s11">
      <input data-format="yyyy-MM-dd" type="text"></input>
    </div>    
  </div>
</div>


</div>

  </div>
  <div id="reminders" class="col s12">Reminders</div>
</div>

<script>

  // CSRF set-up copied from Django docs
  function getCookie(name) {  
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
  }
  var csrftoken = getCookie('csrftoken');
  $.ajaxSetup({
    beforeSend: function(xhr, settings) {
        xhr.setRequestHeader("X-CSRFToken", csrftoken);
    }
  });


    function dismissRequest(o) {
      var p=o.parentNode.parentNode;
    //  console.log(p.firstChild.nextSibling.nextSibling.nextSibling.textContent)
    //  console.log(p.firstChild.nextSibling.nextSibling.nextSibling.nextSibling.nextSibling.textContent.trim())

      var user = p.firstChild.nextSibling.nextSibling.nextSibling.textContent
      var listingTitle = p.firstChild.nextSibling.nextSibling.nextSibling.nextSibling.nextSibling.textContent.trim()

      p.parentNode.removeChild(p);

      var joined=user+"_"+listingTitle
      $.post("/guru/dismiss-request/"+joined)
      .done(function(data) {
      });

    }

    function confirmRequest(o) {
      var p=o.parentNode.parentNode;
      var listingTitle = p.firstChild.nextSibling.nextSibling.nextSibling.textContent
    
      console.log(listingTitle)
      var user = p.firstChild.nextSibling.nextSibling.nextSibling.nextSibling.nextSibling.textContent.trim()
      
      console.log(user)
      p.parentNode.removeChild(p);

      $.post("/guru/confirm-request", {'user': user, 'listingTitle': listingTitle })
      .done(function(data) {
      });

    }

</script>


{% endblock %}

guru/templates/guru/base.html
{% load staticfiles %}

<!--http://www.bootply.com/render/128936 
  http://stackoverflow.com/questions/18529274/change-navbar-color-in-twitter-bootstrap-3
-->

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
     {% block title %} {% endblock %}

    <link href= "{% static 'bootstrap-3.3.5-dist/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href= "{% static 'font/font-awesome-4.4.0/css/font-awesome.min.css'%}" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Oleo+Script' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'css/app.css'%}">
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"media="screen,projection"/>
    <link rel="stylesheet" href="{% static 'animsition/dist/css/animsition.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/materialize-tags.css' %}">
    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.5.0/fullcalendar.min.css" type="text/css">-->
  </head>

 <body>

    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/modals.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/materialize-tags.js' %}"></script>
    <!--<script type='text/javascript' src="{% static 'js/moment.js' %}"></script>-->
    <script type="text/javascript" src="{% static 'js/typehead.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/dates.js' %}"></script>
   <!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.5.0/fullcalendar.min.js"></script>
    <script type='text/javascript' src="{% static 'js/gcal.js' %}"></script>-->
  
     
     
    <nav class="navbar navbar-default navbar-fixed-top blue" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">TimeShare</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/guru/logout">Log out</a></li>
          </ul>
          <div class="col-sm-5 col-md-5 pull-left">
        
        <form method="post" action="/guru/search"> {% csrf_token %}
        <div class="input-field">
          <input type='text' name='q' id="search id_q" type="search">
          <label for="search"><i class="material-icons">search</i></label>
          
        </div>
      </form>



   
        </div>
            <ul class="nav navbar-nav navbar-left">
            <li><a href="/guru/newlisting"><i class="fa fa-pencil-square-o fa-2x"></i></a></li>
            
            <li><a href="/guru/alllistings"><i class="fa fa-list fa-2x"></i></a></li>
          </ul>

        </div>
      </div>
</nav>

<div class="container-fluid">
      
      <div class="row">
        
         <div class="col-sm-3 col-md-2" id="sidebar" role="navigation">
           
            <ul class="nav nav-sidebar nav-fixed">
              <li id="userli">
              <div class="user-info-wrap"> 
                <div class="user-image">
                  <img src="/guru{{ image.url }}" alt="{{image.url}}" class="img-circle" width="65" height="65">
                </div>
                <div class="user-info">
                  <div class="username">{{currUser.first_name}} {{currUser.last_name}}</div>

                  <a href="/guru/profile/{{currUser.id}}">Profile</a>
                </div>
              </div>
            </li>

            
              </a></li>
              <li><a href="/guru/activity">
                <span class="text"> My Activity </span></a>
              </li>
              <hr>
              <li><a href="/guru/inbox"><i class="glyphicon glyphicon-envelope"></i>
                <span class="text"> Inbox </span></a>
              </li>
              <li><a href="/guru/reminders"><i class="glyphicon glyphicon-bell"></i>
                <span class="text"> Reminders </span></a>
              </li>
              <li><a href="/guru/myreviews"><i class="glyphicon glyphicon-star"></i>
                <span class="text"> Reviews 
                  {% if numNotReviewed > 0 %}
                  <span class="new badge">{{numNotReviewed}}</span>
                  {% endif %}
                </span> </a>
              </li>
              <li><a href="/guru/settings"><i class="glyphicon glyphicon-cog"></i>
                <span class="text"> Change Preferences </span> </a>
              </li>

            </ul>
          
        </div>

        <!-- main section of page -->
        <div class="col-sm-9 col-md-10 main">
          {% block mainsection %} {% endblock %}
        </div><!-- main section-->
      </div><!-- end row -->
    </div> <!-- end container -->

  </body>
</html>

guru/templates/guru/calendar.html
{% extends "guru/base.html" %}


{% block title %}
<title> guru | calendar </title>
{% endblock %}

{% block mainsection %}
  <div class="col-md-12">
        <div id="calendar"> </div>
  </div>

  <script>
    $(document).ready(function() {
    $('#calendar').fullCalendar({
        googleCalendarApiKey: 'AIzaSyC1TITZmqLAwg3rhxAidZ_sUMv6ojbv38Y',
        events: {
            googleCalendarId: 'cathy.94@gmail.com'
        }
    });
});
  </script>
{% endblock %}

guru/templates/guru/compose.html
{% extends "guru/base.html" %}
{% load staticfiles %}
<!-- autocomplete + tag lib: 
    http://www.jqueryscript.net/demo/Material-Design-Tags-Input-Plugin-with-jQuery-Materialize-Tags/
-->
{% block title %}
<title> guru | compose </title>
{% endblock %}

{% block mainsection %}
<div class="col-md-12">
  <div class="row">
    <br>
  </div>

    <div class="row">
    <form class="col s12" action="/guru/sendmessage" method="post">
      <div class="row">

        <div class="input-field col s12">
            <input type="text" id="to" class="form-control" value='{{msgusername}}' data-role="materialtags" name="to"/>
            <label for="to">To</label>
        
            <br>
            <br>
        </div>

        <div class="input-field col s12">
          <input id="subject" type="text" class="validate" name="subject">
          <label for="subject">Subject</label>
        </div>

        <div class="input-field col s12">
          <textarea id="textarea1" class="materialize-textarea" name="description"></textarea>
          <label for="body">Body</label>
        </div>

      </div>


      <button class="waves-effect waves-light btn blue searchBtn" type="submit">Send <i class="material-icons right">send</i>
      </button>
      {% csrf_token %}
    </form>

  </div>
    
</div>

<script>
    var usernames = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        prefetch: {
            url: 'getusernames', 
        } 
        
    });

    usernames.initialize();

    $('input#to').materialtags({
        typeaheadjs: {
            name: 'usernames',
            displayKey: 'name',
            valueKey: 'name',
            source: usernames.ttAdapter()
        }
    });
    var wat = $("input#to").materialtags('items')
</script>

{% endblock %}

guru/templates/guru/editprofile.html
{% extends "guru/base.html" %}


{% block title %}
<title> guru | edit profile </title>
{% endblock %}

{% block mainsection %}
<div class="col-md-12">
    <h1> Edit Profile </h1>
  <img src="/guru{{ profile.picture.url }}" alt="{{profile.picture}}">

  <form enctype="multipart/form-data" action="{% url 'editprofile'%}" method="post">
    <table>
    
    {{form}}
    
    </table>
    <input type="submit" value="Save">
    {% csrf_token %}
  </form>

  
  <a href="{% url 'home' %}"><button>Cancel</button></a>
    
</div>
{% endblock %}

guru/templates/guru/messageexpanded.html
{% extends "guru/base.html" %}


{% block title %}
<title> guru | messages </title>
{% endblock %}

{% block mainsection %}
<div class="col-md-12">

   <ul class="collapsible" data-collapsible="expandable">
    <!-- original msg -->
    <li>
      <div class="collapsible-header">
        From 
        <a href="/guru/profile/{{fromGuru.user.id}}">
          <div class="chip">
            <img src="/guru{{fromGuru.picture.url}}" alt="Contact Person">
              {{fromGuru.user.username}}
          </div>
        </a>
        <b> {{message.subject}} </b> - {{message.body|truncatewords:5}}
        <div class="chip emailtime">{{message.date}}</div>
      </div>
      <div class="collapsible-body" style="display: none;">
        <p>{{message.body}}</p>
      </div>
    </li>
    
    <!-- replies -->
    {% if message.reply_set.all %}
    {% for reply in message.reply_set.all %}
    <li>
      <div class="collapsible-header">
        From 
        <a href="/guru/profile/{{reply.fromGuru.user.id}}">
          <div class="chip">
            <img src="/guru{{reply.fromGuru.picture.url}}" alt="Contact Person">
              {{reply.fromGuru.user.username}}
          </div>
        </a>
        {{reply.body|truncatewords:5}}
        <div class="chip emailtime">{{reply.date}}</div>
      </div>
      <div class="collapsible-body" style="display: none;">
        <p>{{reply.body}}</p>
      </div>
    </li>

  {% endfor %}
  {% endif %}
   </ul>
  }

  <div class="card white">
    <div class="card-content blue-text">
      <div class="row">
        <form class="col s12" action="/guru/sendreply" method="post">
          <div class="row">
            <div class="input-field col s12">
              <textarea id="textarea1" class="materialize-textarea" name="replytext"></textarea>
              <label for="textarea1">Reply</label>
            </div>
          </div>

          <input type="hidden" name="messageId" value="{{message.id}}">
          <button class="waves-effect waves-light btn blue searchBtn" type="submit">Send <i class="material-icons right">send</i>
          </button>
          {% csrf_token %}
        </form>
      </div>
    </div>
  </div>
       
</div>
{% endblock %}